.control_service_retry:
  retry_options:
    max: 1
    when:
      - always

.images:dind:
  image: docker:20.10.22
  variables:
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:20.10.22-dind


# TODO: automatically rebuild image on vdk-heartbeat change
control_service_vdk_heartbeat_release:
  image: docker:20.10.22
  services:
    - name: docker:20.10.22-dind
      alias: thedockerhost
  variables:
    DOCKER_HOST: tcp://thedockerhost:2375
    DOCKER_TLS_CERTDIR: ""
  stage: release
  before_script:
    - docker info
  script:
    - export CHART_NAME=pipelines-control-service
    - export CHART_VERSION=$(cat projects/control-service/projects/helm_charts/$CHART_NAME/version.txt | grep -o '^[0-9]\+\.[0-9]\+').$CI_PIPELINE_ID
    - export VDK_HEARTBEAT_TEST_NAME=$CHART_NAME-integration-tests:$CHART_VERSION
    - export VDK_HEARTBEAT_IMAGE_NAME="$VDK_DOCKER_REGISTRY_URL/$VDK_HEARTBEAT_TEST_NAME"
    - docker login $VDK_DOCKER_REGISTRY_URL --username $VDK_DOCKER_REGISTRY_USERNAME --password $VDK_DOCKER_REGISTRY_PASSWORD
    - cd projects/control-service/cicd
    - docker build --tag $VDK_HEARTBEAT_IMAGE_NAME -f Dockerfile.vdk.heartbeat .
  retry: !reference [.control_service_retry, retry_options]
  only:
    refs:
      - external_pull_requests
